var emotionJson = [
		    {"name": "Expression_1","text": "[微笑]"},
		    {"name": "Expression_2","text": "[撇嘴]"},
		    {"name": "Expression_3","text": "[开心]"},
		    {"name": "Expression_4","text": "[发呆]"},
		    {"name": "Expression_5","text": "[得意]"},
		    {"name": "Expression_6","text": "[流泪]"},
		    {"name": "Expression_7","text": "[害羞]"},
		    {"name": "Expression_8","text": "[闭嘴]"},
		    {"name": "Expression_9","text": "[睡]"},
		    {"name": "Expression_10","text": "[大哭]"},
		    {"name": "Expression_11","text": "[尴尬]"},
		    {"name": "Expression_12","text": "[发怒]"},
		    {"name": "Expression_13","text": "[调皮]"},
		    {"name": "Expression_14","text": "[呲牙]"},
		    {"name": "Expression_15","text": "[惊吓]"},
		    {"name": "Expression_16","text": "[难过]"},
		    {"name": "Expression_17","text": "[耍酷]"},
		    {"name": "Expression_18","text": "[冒汗]"},
		    {"name": "Expression_19","text": "[抓狂]"},
		    {"name": "Expression_20","text": "[吐]"},
		    {"name": "Expression_21","text": "[偷笑]"},
		    {"name": "Expression_22","text": "[可爱]"},
		    {"name": "Expression_23","text": "[白眼]"},
		    {"name": "Expression_24","text": "[傲慢]"},
		    {"name": "Expression_25","text": "[饥饿]"},
		    {"name": "Expression_26","text": "[哈欠]"},
		    {"name": "Expression_27","text": "[恐惧]"},
		    {"name": "Expression_28","text": "[流汗]"},
		    {"name": "Expression_29","text": "[大笑]"},
		    {"name": "Expression_31","text": "[奋斗]"},
		    {"name": "Expression_32","text": "[咒骂]"},
		    {"name": "Expression_33","text": "[疑问]"},
		    {"name": "Expression_34","text": "[嘘]"},
		    {"name": "Expression_35","text": "[晕]"},
		    {"name": "Expression_36","text": "[折磨]"},
		    {"name": "Expression_37","text": "[衰]"},
		    {"name": "Expression_39","text": "[敲打]"},
		    {"name": "Expression_40","text": "[再见]"},
		    {"name": "Expression_41","text": "[擦汗]"},
		    {"name": "Expression_42","text": "[抠鼻]"},
		    {"name": "Expression_43","text": "[鼓掌]"},
		    {"name": "Expression_45","text": "[坏笑]"},
		    {"name": "Expression_46","text": "[左哼哼]"},
		    {"name": "Expression_47","text": "[右哼哼]"},
		    {"name": "Expression_48","text": "[犯困]"},
		    {"name": "Expression_49","text": "[鄙视]"},
		    {"name": "Expression_50","text": "[委屈]"},
		    {"name": "Expression_51","text": "[快哭了]"},
		    {"name": "Expression_52","text": "[阴险]"},
		    {"name": "Expression_53","text": "[亲亲]"},
		    {"name": "Expression_54","text": "[嫌弃]"},
		    {"name": "Expression_55","text": "[可怜]"}
	];

// 定义数据出口
module.exports = {
   emotionData: emotionJson
}